appName: shippingservice
appImage: gcr.io/google-samples/microservices-demo/shippingservice
appVersion: v0.3.6
appReplicas: 2
containerPort: 50051
containerEnvVars:
- name: PORT
  value: "50051"


servicePort: 50051